#!/usr/bin/env python
import sys
def distance(cities,type):
  connected_graphs = list()
  total_dist = 0
  for i in range(0,len(cities)-1):
    dist = calc_distance(list([cities[i][1],cities[i+1][1]]))
    connected_graphs.append(list([cities[i][0],cities[i+1][0],dist]))
    total_dist+= dist

  print "\nSuccess! Your vacation itinerary is:"
  for i in connected_graphs:
    print "\t"+i[0]+"-> "+i[1]+": "+str(i[2])
  print ("Total distance covered in your trip: {:,}".format(total_dist)),
  print type+'\n'
def calc_distance(coordinates):
  return pow(pow(coordinates[0][0]-coordinates[1][0],2)+pow(coordinates[1][1]-coordinates[0][1],2),0.5)

if len(sys.argv) > 3:
  print "too many arguments!" 
else:
  f = open("distanceFile",'r')
  items = list()
  for i in f:
    items.append(i)
  for i in range(0,len(items)):
    items[i] = items[i].split('|')
    items[i][1] = items[i][1].split(' ')[1]
    items[i][1] = items[i][1].split('\n')[0]
    items[i][1] = items[i][1].split(',')
    items[i][1][0] = int(items[i][1][0])
    items[i][1][1] = int(items[i][1][1]) 
  if len(sys.argv) == 3:
    if (sys.argv[2][0] != '-'):
      print "Incorrect 3rd parameter. Must be -type=miles or -type=km"
    else:
      dist_type = sys.argv[2].split('-')[1]
      if dist_type != "miles" and dist_type != "km":
        print "type must be miles or km only"
      else:
        distance(items,dist_type)
  else:
    distance(items,"miles")
